apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet-a
spec:
  forProvider:
    name: example-subnet-a
    networkIdRef:
      name: example-net
    v4CidrBlocks:
      - 10.0.0.0/24
    folderIdRef:
      name: example-folder
    zone: ru-central1-a
  providerConfigRef:
    name: example
