apiVersion: resourcemanager.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIamBinding
metadata:
  name: crossplane-preprod
spec:
  forProvider:
    members:
      - serviceAccount:<sa-id>
    role: editor
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example
