apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: example-sa-key
spec:
  forProvider:
    description: "static access key for object storage"
    serviceAccountIdRef:
      name: example-sa
  providerConfigRef:
    name: example