apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountStaticAccessKey
metadata:
  name: example-sa-static-key
spec:
  forProvider:
    description: "static access key for object storage"
    serviceAccountIdRef:
      name: example-sa
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: sa-key-conn
    namespace: crossplane-system