apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-sa
spec:
  forProvider:
    name: example-sa
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example