apiVersion: kubernetes.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    name: example-cluster
    description: provider-jet-yc cluster
    networkIdRef:
      name: example-net
    master:
      - version: "1.21"
        zonal:
          - zone: ru-central1-a
            subnetIdRef:
              name: example-subnet-a
        publicIp: true
        maintenancePolicy:
          - autoUpgrade: true
            maintenanceWindow:
              - startTime: "15:00"
                duration: "3h"
    serviceAccountIdRef:
      name: example-sa
    nodeServiceAccountIdRef:
      name: example-sa
    releaseChannel: RAPID
    networkPolicyProvider: CALICO
    kmsProvider:
      - keyIdRef:
          name: example-sk
  providerConfigRef:
    name: example