apiVersion: container.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: example-repository
spec:
  forProvider:
    name: "<registry-id>/test-repository"
  providerConfigRef:
    name: example